openapi: 3.0.3
info:
  title: Lopez IT Welt API
  version: 1.0.0
  description: API für Services, Nutzer, Bestellungen und Tickets
servers:
  - url: https://api.lopez-it-welt.de/v1
paths:
  /services:
    get:
      summary: Liste aller Services
      responses:
        "200":
          description: Erfolgreich
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Service"
    post:
      summary: Service anlegen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServiceInput"
      responses:
        "201":
          description: Erstellt
  /services/{id}:
    get:
      summary: Service-Details
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Erfolgreich
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Service"
  /users:
    post:
      summary: Nutzer anlegen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInput"
      responses:
        "201":
          description: Erstellt
    get:
      summary: Nutzerliste
      responses:
        "200":
          description: Erfolgreich
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  /orders:
    get:
      summary: Bestellungen abrufen
      responses:
        "200":
          description: Erfolgreich
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
  /tickets:
    post:
      summary: Ticket erstellen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TicketInput"
      responses:
        "201":
          description: Erstellt
    get:
      summary: Tickets abrufen
      responses:
        "200":
          description: Erfolgreich
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ticket"
components:
  schemas:
    Service:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        category:
          type: string
        price:
          type: number
    ServiceInput:
      type: object
      properties:
        name:
          type: string
        category:
          type: string
        price:
          type: number
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        role:
          type: string
    UserInput:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        role:
          type: string
    Order:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        serviceId:
          type: integer
        status:
          type: string
    Ticket:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        subject:
          type: string
        status:
          type: string
    TicketInput:
      type: object
      properties:
        userId:
          type: integer
        subject:
          type: string
        description:
          type: string
