// =====================================================
// AGENT-B BUILDER – Enterprise++ Dev-Orchestrator
// =====================================================
// Erstellt: 2025-12-04
// Zweck: Code-Generierung basierend auf Agent-A Plan
// Status: ✅ PHASE 2 – Build
// =====================================================
//
// SICHERHEITSHINWEISE:
// - Arbeitet NUR mit lopez_it_welt_dev
// - KEINE destruktiven Operationen
// - KEINE init/reset Funktionen
// - Erzeugt nur Code-VORSCHLÄGE, führt nichts aus
// =====================================================

import { getConnection } from "../database";
import { RowDataPacket, ResultSetHeader } from "mysql2/promise";
import { DevTaskStep, DevTasksService } from "../dev-tasks-service";
import { getProvider } from "../ai/core/ai-provider-factory";

// =====================================================
// TYPEN
// =====================================================

export interface CodeChange {
  id: number;
  task_id: number;
  step_id: number;
  file_path: string;
  code_type: "new" | "modify" | "delete";
  code_before: string | null;
  code_after: string;
  explanation: string;
  status: "pending" | "approved" | "rejected" | "applied";
  created_at: Date;
  updated_at: Date;
}

export interface BuildResult {
  success: boolean;
  task_id: number;
  changes: CodeChange[];
  summary: string;
  warnings: string[];
}

// =====================================================
// AGENT-B BUILDER SERVICE
// =====================================================

export class AgentBBuilder {
  
  // -------------------------------------------------
  // PLAN LADEN
  // -------------------------------------------------

  /**
   * Lädt den Plan (Steps) für einen Task
   */
  static async loadPlan(taskId: number): Promise<{
    task: any;
    steps: DevTaskStep[];
  }> {
    const task = await DevTasksService.getTaskById(taskId);
    if (!task) {
      throw new Error(`Task ${taskId} nicht gefunden`);
    }
    
    // Erlaubte Status: "planned" (neu geplant) oder "open" (nach Recheck wieder geöffnet)
    const allowedStatuses = ["planned", "open"];
    if (!allowedStatuses.includes(task.status)) {
      throw new Error(`Task ${taskId} hat Status '${task.status}', erwartet 'planned' oder 'open'`);
    }
    
    const steps = await DevTasksService.getStepsForTask(taskId);
    return { task, steps };
  }

  // -------------------------------------------------
  // CODE GENERIERUNG
  // -------------------------------------------------

  /**
   * Generiert Code für einen einzelnen Step
   * Mock-Modus wenn AI-Provider unsicher
   */
  static async generateCodeForStep(
    step: DevTaskStep,
    taskContext: { title: string; description: string; type: string }
  ): Promise<{
    file_path: string;
    code_type: "new" | "modify" | "delete";
    code_before: string | null;
    code_after: string;
    explanation: string;
  }> {
    try {
      const aiProvider = getProvider();
      
      // Prüfe ob Mock-Modus
      if (!aiProvider || aiProvider.name === "mock") {
        return this.generateMockCode(step, taskContext);
      }
      
      // Echte AI-Generierung
      const systemPrompt = "Du bist Agent-B, ein Enterprise++ Code-Generator. Generiere sauberen, typisierten TypeScript-Code.";
      const userPrompt = this.buildCodePrompt(step, taskContext);
      const fullPrompt = `${systemPrompt}\n\n${userPrompt}`;
      const responseContent = await aiProvider.requestText(fullPrompt, {
        maxTokens: 4000,
        temperature: 0.2
      });
      
      // Parse AI-Antwort
      return this.parseAICodeResponse(responseContent, step);
      
    } catch (error) {
      console.warn(`[Agent-B] AI-Fehler, verwende Mock:`, error);
      return this.generateMockCode(step, taskContext);
    }
  }

  /**
   * Mock-Code-Generierung wenn AI nicht verfügbar
   */
  private static generateMockCode(
    step: DevTaskStep,
    taskContext: { title: string; description: string; type: string }
  ): {
    file_path: string;
    code_type: "new" | "modify" | "delete";
    code_before: string | null;
    code_after: string;
    explanation: string;
  } {
    const stepTitle = step.title.toLowerCase();
    
    // Intelligentes Mock basierend auf Step-Titel
    if (stepTitle.includes("backend") || stepTitle.includes("api")) {
      return {
        file_path: `src/app/api/admin/${this.slugify(taskContext.title)}/route.ts`,
        code_type: "new",
        code_before: null,
        code_after: `// =====================================================
// AUTO-GENERATED BY AGENT-B
// Task: ${taskContext.title}
// Step: ${step.title}
// =====================================================

import { NextRequest, NextResponse } from "next/server";

export async function GET(request: NextRequest) {
  try {
    // TODO: Implementierung für "${step.title}"
    // Details: ${step.details || "Keine Details"}
    
    return NextResponse.json({
      success: true,
      message: "API-Endpoint bereit",
      data: {}
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: "Interner Fehler" },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    
    // TODO: Validierung und Verarbeitung
    
    return NextResponse.json({
      success: true,
      message: "Erfolgreich verarbeitet"
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: "Interner Fehler" },
      { status: 500 }
    );
  }
}
`,
        explanation: `Mock-API-Route für Step "${step.title}". Dies ist ein Vorschlag – bitte prüfen und anpassen.`
      };
    }
    
    if (stepTitle.includes("frontend") || stepTitle.includes("ui") || stepTitle.includes("komponente")) {
      return {
        file_path: `src/components/${this.pascalCase(taskContext.title)}.tsx`,
        code_type: "new",
        code_before: null,
        code_after: `// =====================================================
// AUTO-GENERATED BY AGENT-B
// Task: ${taskContext.title}
// Step: ${step.title}
// =====================================================

"use client";

import { useState, useEffect } from "react";

interface ${this.pascalCase(taskContext.title)}Props {
  // TODO: Props definieren
}

export default function ${this.pascalCase(taskContext.title)}({ }: ${this.pascalCase(taskContext.title)}Props) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // TODO: Initialisierung für "${step.title}"
  }, []);

  if (loading) {
    return <div className="p-4">Laden...</div>;
  }

  if (error) {
    return <div className="p-4 text-red-500">{error}</div>;
  }

  return (
    <div className="p-4">
      {/* TODO: UI für "${step.title}" */}
      <h2 className="text-xl font-bold">${taskContext.title}</h2>
      <p className="text-gray-500">${step.details || "Implementierung ausstehend"}</p>
    </div>
  );
}
`,
        explanation: `Mock-React-Komponente für Step "${step.title}". Dies ist ein Vorschlag – bitte prüfen und anpassen.`
      };
    }
    
    if (stepTitle.includes("test")) {
      return {
        file_path: `src/__tests__/${this.slugify(taskContext.title)}.test.ts`,
        code_type: "new",
        code_before: null,
        code_after: `// =====================================================
// AUTO-GENERATED BY AGENT-B
// Task: ${taskContext.title}
// Step: ${step.title}
// =====================================================

import { describe, it, expect } from "vitest";

describe("${taskContext.title}", () => {
  it("sollte korrekt initialisieren", () => {
    // TODO: Test-Setup
    expect(true).toBe(true);
  });

  it("sollte ${step.title}", () => {
    // TODO: Implementierung testen
    // Details: ${step.details || "Keine Details"}
    expect(true).toBe(true);
  });

  it("sollte Fehler korrekt behandeln", () => {
    // TODO: Error-Handling testen
    expect(true).toBe(true);
  });
});
`,
        explanation: `Mock-Test-Datei für Step "${step.title}". Dies ist ein Vorschlag – bitte prüfen und anpassen.`
      };
    }
    
    // Fallback: Generische Logik-Datei
    return {
      file_path: `src/lib/${this.slugify(taskContext.title)}.ts`,
      code_type: "new",
      code_before: null,
      code_after: `// =====================================================
// AUTO-GENERATED BY AGENT-B
// Task: ${taskContext.title}
// Step: ${step.title}
// =====================================================

/**
 * ${taskContext.description}
 */

export interface ${this.pascalCase(taskContext.title)}Config {
  // TODO: Konfiguration definieren
}

export class ${this.pascalCase(taskContext.title)}Service {
  
  /**
   * ${step.title}
   * ${step.details || ""}
   */
  static async execute(config: ${this.pascalCase(taskContext.title)}Config): Promise<void> {
    // TODO: Implementierung
    console.log("[${this.pascalCase(taskContext.title)}Service] Ausführung gestartet");
  }
}

export default ${this.pascalCase(taskContext.title)}Service;
`,
      explanation: `Mock-Service für Step "${step.title}". Dies ist ein Vorschlag – bitte prüfen und anpassen.`
    };
  }

  /**
   * Baut den Prompt für AI-Code-Generierung
   */
  private static buildCodePrompt(
    step: DevTaskStep,
    taskContext: { title: string; description: string; type: string }
  ): string {
    return `
Du bist Agent-B im Enterprise++ Dev-Orchestrator.

AUFGABE: Generiere Code für folgenden Schritt:

## Task
- Titel: ${taskContext.title}
- Beschreibung: ${taskContext.description}
- Typ: ${taskContext.type}

## Aktueller Schritt
- Nummer: ${step.step_number}
- Titel: ${step.title}
- Details: ${step.details || "Keine"}
- Geschätzter Aufwand: ${step.estimated_effort || "Nicht angegeben"}

## Anforderungen
- TypeScript/React (Next.js 14+ App Router)
- Enterprise++ Standards
- Vollständig typisiert
- Kommentiert
- DSGVO-konform falls relevant

Antworte im JSON-Format:
{
  "file_path": "src/...",
  "code_type": "new|modify|delete",
  "code_before": null,
  "code_after": "// vollständiger Code",
  "explanation": "Kurze Erklärung"
}
`;
  }

  /**
   * Parst die AI-Antwort
   */
  private static parseAICodeResponse(
    response: string,
    step: DevTaskStep
  ): {
    file_path: string;
    code_type: "new" | "modify" | "delete";
    code_before: string | null;
    code_after: string;
    explanation: string;
  } {
    try {
      // Versuche JSON zu parsen
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        return {
          file_path: parsed.file_path || `src/generated/step-${step.step_number}.ts`,
          code_type: parsed.code_type || "new",
          code_before: parsed.code_before || null,
          code_after: parsed.code_after || "// Code konnte nicht generiert werden",
          explanation: parsed.explanation || "AI-generierter Code"
        };
      }
    } catch (e) {
      console.warn("[Agent-B] Konnte AI-Antwort nicht parsen");
    }
    
    // Fallback
    return {
      file_path: `src/generated/step-${step.step_number}.ts`,
      code_type: "new",
      code_before: null,
      code_after: response,
      explanation: "AI-generierter Code (unstrukturiert)"
    };
  }

  // -------------------------------------------------
  // CODE SPEICHERN
  // -------------------------------------------------

  /**
   * Speichert einen Code-Change in der Datenbank
   */
  static async saveCodeChange(
    taskId: number,
    stepId: number,
    change: {
      file_path: string;
      code_type: "new" | "modify" | "delete";
      code_before: string | null;
      code_after: string;
      explanation: string;
    }
  ): Promise<CodeChange> {
    const pool = await getConnection();
    
    const [result] = await pool.execute<ResultSetHeader>(
      `INSERT INTO dev_code_changes 
        (task_id, step_id, file_path, code_type, code_before, code_after, explanation, status) 
       VALUES (?, ?, ?, ?, ?, ?, ?, 'pending')`,
      [
        taskId,
        stepId,
        change.file_path,
        change.code_type,
        change.code_before,
        change.code_after,
        change.explanation
      ]
    );

    const changeId = result.insertId;
    
    const [rows] = await pool.execute<RowDataPacket[]>(
      `SELECT * FROM dev_code_changes WHERE id = ?`,
      [changeId]
    );
    
    return rows[0] as CodeChange;
  }

  /**
   * Lädt alle Code-Changes für einen Task
   */
  static async getCodeChangesForTask(taskId: number): Promise<CodeChange[]> {
    const pool = await getConnection();
    
    const [rows] = await pool.execute<RowDataPacket[]>(
      `SELECT * FROM dev_code_changes WHERE task_id = ? ORDER BY id ASC`,
      [taskId]
    );
    
    return rows as CodeChange[];
  }

  // -------------------------------------------------
  // BUILD AUSFÜHREN
  // -------------------------------------------------

  /**
   * Führt den kompletten Build für einen Task aus
   */
  static async runBuild(taskId: number): Promise<BuildResult> {
    const warnings: string[] = [];
    const changes: CodeChange[] = [];
    
    // 1. Plan laden
    const { task, steps } = await this.loadPlan(taskId);
    
    if (steps.length === 0) {
      throw new Error("Keine Plan-Schritte vorhanden");
    }
    
    // 2. Task-Status auf 'coding' setzen
    await DevTasksService.updateTaskStatus(taskId, "coding");
    
    // 3. Für jeden Step Code generieren
    for (const step of steps) {
      try {
        const codeResult = await this.generateCodeForStep(step, {
          title: task.title,
          description: task.description,
          type: task.type
        });
        
        // Speichern
        const savedChange = await this.saveCodeChange(taskId, step.id, codeResult);
        changes.push(savedChange);
        
      } catch (error) {
        warnings.push(`Step ${step.step_number} (${step.title}): ${error}`);
      }
    }
    
    return {
      success: true,
      task_id: taskId,
      changes,
      summary: `${changes.length} Code-Änderungen für ${steps.length} Steps generiert`,
      warnings
    };
  }

  // -------------------------------------------------
  // HILFSFUNKTIONEN
  // -------------------------------------------------

  private static slugify(text: string): string {
    return text
      .toLowerCase()
      .replace(/[äöüß]/g, (c) => ({ ä: "ae", ö: "oe", ü: "ue", ß: "ss" }[c] || c))
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
  }

  private static pascalCase(text: string): string {
    return text
      .replace(/[äöüß]/g, (c) => ({ ä: "ae", ö: "oe", ü: "ue", ß: "ss" }[c] || c))
      .replace(/[^a-zA-Z0-9]+/g, " ")
      .split(" ")
      .filter(Boolean)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join("");
  }
}

export default AgentBBuilder;







